import {StyleSheet} from 'react-native';
import {
  verticalScale,
  horizontalScale,
  verticalMarginScale,
  //   horizontalMarginScale,
  radiusScale,
  fontScale,
  horizontalMarginScale,
} from '../../utils/DimensionConstant';
import {Fonts} from '../../utils/Constants';
const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    // backgroundColor: 'white',
    // height:"100%",
  },
  header: {
    height: verticalScale(100),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    paddingBottom: 0,
    marginVertical: verticalMarginScale(8),
  },
  backIcon: {
    height: verticalScale(40),
    width: horizontalScale(40),
  },
  headerTxt: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(22),
    color: '#FFFFFF',
  },
  questionContainer: {
    height: verticalScale(42),
    width: horizontalScale(129),
    padding: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: verticalMarginScale(18),
    // backgroundColor: 'red',
    left: 12,
  },
  questionText: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(16),
    color: '#FFFFFF',
  },
  question: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(26),
    color: '#FFFFFF',
    padding: 15,
    marginTop: verticalMarginScale(10),
    height: verticalScale(150),
    // backgroundColor: 'red',
  },
  Container: {
    position: 'relative',
    height: verticalScale(600),
    marginTop: verticalMarginScale(10),
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: radiusScale(40),
    borderTopRightRadius: radiusScale(40),
    paddingHorizontal: horizontalScale(25),
    paddingVertical: verticalScale(30),
  },
  optionHead: {
    fontFamily: Fonts.Bold,
    fontSize: fontScale(18),
    color: '#292D32',
    letterSpacing: 0.25,
  },
  option: {
    height: verticalScale(62),
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    padding: 15,
    borderRadius: radiusScale(14),
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#EBEBEB',
  },
  selectedOption: {
    backgroundColor: '#0099FF0D',
    borderColor: '#0099FF',
    borderWidth: 0.5,
  },
  radioText: {
    fontSize: 18,
    marginRight: 10,
    color: '#888',
  },
  selectedRadioText: {
    color: '#007bff',
    fontWeight: 'bold',
  },
  optionText: {
    fontFamily: Fonts.Regular,
    fontSize: fontScale(16),
    color: '#AEAEB2',
  },
  selectedOptionText: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(16),
    color: '#0099FF',
  },
  optionIcon: {
    height: verticalScale(19.5),
    width: horizontalScale(19),
    borderRadius: radiusScale(9.5),
  },
  buttonContainer: {
    height: verticalScale(52.38),
    width: horizontalScale(350),
    // backgroundColor:'yellow',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: verticalMarginScale(60),
    // marginBottom: verticalMarginScale(2000),
  },
  backButton: {
    height: verticalScale(52.38),
    width: horizontalScale(120),
    borderRadius: radiusScale(16),
    backgroundColor: '#F3F0FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backText: {
    fontFamily: Fonts.Regular,
    fontSize: fontScale(16),
    color: '#0099FF',
  },
  nextButton: {
    height: verticalScale(52.38),
    width: horizontalScale(220),
    borderRadius: radiusScale(16),
    backgroundColor: '#0099FF',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  nextArrow: {
    height: verticalScale(21.73),
    width: horizontalScale(41.39),
  },
  nextText: {
    fontFamily: Fonts.Regular,
    fontSize: fontScale(16),
    color: '#FFFFFF',
    marginRight: horizontalMarginScale(3),
  },
});

export default styles;
