import {StyleSheet} from 'react-native';
import {
  verticalScale,
  horizontalScale,
  verticalMarginScale,
  horizontalMarginScale,
  radiusScale,
  fontScale,
} from '../../utils/DimensionConstant';
import {Fonts} from '../../utils/Constants';

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: 'white',
    // height:"100%",
  },
  header: {
    height: verticalScale(110),
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    padding: 20,
    // backgroundColor: 'red',
    marginTop: verticalMarginScale(15),
    marginBottom: verticalMarginScale(15),
  },
  backIcon: {
    height: verticalScale(40),
    width: horizontalScale(40),
  },
  headerTxt: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(22),
    color: '#FFFFFF',
    letterSpacing: 0.25,
  },
  Container: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: radiusScale(40),
    borderTopRightRadius: radiusScale(40),
    paddingHorizontal: horizontalScale(25),
    paddingVertical: verticalScale(25),
  },
  docContainer: {
    height: verticalScale(112),
    flexDirection: 'row',
    alignItems: 'center',
    // backgroundColor: 'yellow',
  },
  docProfile: {
    height: verticalScale(112),
    width: horizontalScale(112),
    borderRadius: radiusScale(14),
    marginRight: horizontalMarginScale(8),
  },
  docDetails: {
    height: verticalScale(73),
    width: horizontalScale(199),
    justifyContent: 'space-between',
    // alignItems:'center',
    // backgroundColor: 'red',
  },
  docName: {
    // alignItems:'flex-start',
    fontFamily: Fonts.Bold,
    fontSize: fontScale(16),
    color: '#323232',
  },
  docSpec: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(14),
    color: '#323232',
  },
  docRating: {
    flexDirection: 'row',
    alignItems: 'center',
    // backgroundColor:'green',
  },
  starIcon: {
    height: verticalScale(15),
    width: horizontalScale(15),
    marginRight: horizontalMarginScale(4),
  },
  ratingTxt: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(13),
    color: '#323232',
  },
  line: {
    marginTop: verticalMarginScale(20),
    // width: horizontalScale(350),
    borderWidth: 0.2,
    borderColor: '#518CFFA6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  head: {
    fontFamily: Fonts.Bold,
    fontSize: fontScale(18),
    color: '#595959',
    marginVertical: verticalMarginScale(20),
  },
  subContainer: {
    // backgroundColor:'red',
    height: verticalScale(67),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tab: {
    height: verticalScale(67),
    width: horizontalScale(167),
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: radiusScale(26),
    borderWidth: 0.5,
    borderColor: '#C1C1C1',
    justifyContent: 'center',
  },
  tabTxt: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(16),
    color: '#323232',
  },
  selectedTab: {
    borderColor: '#0099FF',
  },
  selectedTabTxt: {
    fontFamily: Fonts.Bold,
  },
  typeIcon: {
    height: verticalScale(30),
    width: horizontalScale(30),
    marginRight: horizontalMarginScale(7),
  },
  head1: {
    marginTop: verticalMarginScale(25),
  },
  modeTab: {
    flexDirection: 'row',
    alignItems: 'center',
    height: verticalScale(67),
    width: horizontalScale(110),
    borderRadius: radiusScale(26),
    backgroundColor: '#F4F8FF',
    justifyContent: 'center',
  },
  modeIcon: {
    height: verticalScale(24),
    width: horizontalScale(24),
    marginRight: horizontalMarginScale(9),
  },
  modeTxt: {
    fontFamily: Fonts.Bold,
    fontSize: fontScale(16),
    color: '#81AEFDBD',
  },
  selectedMode: {
    backgroundColor: '#FFFFFF',
    borderColor: '#0099FF',
    borderWidth: 0.5,
  },
  selectedModeTxt: {
    color: '#0099FF',
  },
  locationTab: {
    flexDirection: 'row',
    // justifyContent:'center',
    alignItems: 'center',
    height: verticalScale(67),
    paddingVertical: verticalScale(11),
    paddingLeft: horizontalScale(20),
    borderRadius: radiusScale(16),
    backgroundColor: '#F4F8FF',
    marginBottom: verticalMarginScale(12),
  },
  selectedLocation: {
    borderWidth: 0.5,
    borderColor: '#0099FF',
    backgroundColor: '#FFFFFF',
  },
  locationIcon: {
    height: verticalScale(19),
    width: horizontalScale(19),
    marginRight: horizontalMarginScale(9),
  },
  LocationTxt: {
    fontFamily: Fonts.Regular,
    fontSize: fontScale(16),
    color: '#323232',
  },
  selectedLocationTxt: {
    fontFamily: Fonts.SemiBold,
  },
  subHead: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(16),
    color: '#595959',
    marginVertical: verticalMarginScale(10),
    lineHeight: 28,
    letterSpacing: 0.2,
  },
  dateTab: {
    height: verticalScale(76),
    width: horizontalScale(72),
    borderRadius: radiusScale(12),
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginRight: horizontalMarginScale(10),
    justifyContent: 'center',
    alignItems: 'center',
  },
  dayText: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(12),
    color: '#18181B',
  },
  dateText: {
    fontFamily: Fonts.Bold,
    fontSize: fontScale(20),
    color: '#323232',
  },
  selectedDateTab: {
    backgroundColor: '#0099FF',
    borderWidth: 0,
  },
  selectedDayText: {
    color: '#FFFFFF',
  },
  selectedDateText: {
    color: '#FFFFFF',
  },
  disableDateTab: {
    backgroundColor: '#E5E7EB',
  },
  disableDayText: {
    color: '#A1A1AA',
  },
  disableDateText: {
    color: '#A1A1AA',
  },
  timeTab: {
    height: verticalScale(28),
    width: horizontalScale(73),
    borderRadius: radiusScale(12),
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginRight: horizontalMarginScale(10),
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeTxt: {
    color: '#18181B',
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(12),
  },
  uploadContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: verticalMarginScale(15),
    marginBottom: verticalMarginScale(150),
  },
  questionTxt: {
    color: '#595959',
    fontFamily: Fonts.Bold,
    fontSize: fontScale(20),
  },
  linkTxt: {
    color: '#0099FF',
    fontFamily: Fonts.Bold,
    fontSize: fontScale(20),
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: '#0099FF99',
    justifyContent: 'flex-end',
    alignItems: 'center',
    zIndex: 10,
  },
  crossIcon: {
    height: verticalScale(55.5),
    width: horizontalScale(59),
    marginBottom: verticalMarginScale(10),
  },
  uploadHead: {
    fontSize: fontScale(22),
    fontFamily: Fonts.Bold,
    color: '#323232',
  },
  subContainer1: {
    height: verticalScale(98),
    marginVertical: verticalMarginScale(25),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: radiusScale(16),
    borderColor: '#323232',
    borderStyle: 'dashed',
  },
  subContainer2: {
    height: verticalScale(149),
    borderRadius: radiusScale(24),
    backgroundColor: '#F8FBFB',
    borderWidth: 1,
    borderColor: '#F1F1F1',
    marginTop: verticalMarginScale(15),
    marginBottom: verticalMarginScale(10),
    flexDirection: 'row',
    alignItems: 'center',
    // justifyContent:'center',
    paddingVertical: verticalScale(8),
    paddingHorizontal: horizontalScale(10),
  },
  pencilIcon: {
    height: verticalScale(22),
    width: horizontalScale(22),
    alignSelf: 'flex-start',
  },
  detailsContainer: {
    height: verticalScale(100),
    width: horizontalScale(172),
    // backgroundColor:'red',
    justifyContent: 'space-between',
  },
  memberProfile: {
    height: verticalScale(110),
    width: horizontalScale(110),
    marginRight: horizontalMarginScale(8),
    // marginLeft: horizontalMarginScale(8),
  },
  memberName: {
    fontSize: fontScale(16),
    fontFamily: Fonts.Bold,
    color: '#323232',
  },
  info: {
    fontSize: fontScale(14),
    fontFamily: Fonts.SemiBold,
    color: '#323232',
  },
  dataContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  Icon: {
    height: verticalScale(16),
    width: horizontalScale(16),
    marginRight: horizontalMarginScale(8),
  },
  bottomContainer: {
    height: verticalScale(45),
    borderRadius: radiusScale(12),
    backgroundColor: '#EFF9FF',
    marginBottom: verticalMarginScale(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addMemberIcon: {
    height: verticalScale(18),
    width: horizontalScale(18),
    marginRight: horizontalMarginScale(8),
  },
  addMemberTxt: {
    fontSize: fontScale(16),
    fontFamily: Fonts.SemiBold,
    color: '#323232',
  },
  uploadIcon: {
    height: verticalScale(18),
    width: horizontalScale(20),
    marginBottom: verticalMarginScale(8),
  },
  uploadTxt: {
    fontSize: fontScale(16),
    fontFamily: Fonts.SemiBold,
    color: '#898989',
  },
  uploadBtn: {
    height: verticalScale(66),
    backgroundColor: '#0099FF',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radiusScale(16),
    marginBottom: verticalMarginScale(20),
  },
  uploadText: {
    fontSize: fontScale(16),
    fontFamily: Fonts.SemiBold,
    color: '#FFFFFF',
  },
  fixedButtonContainer: {
    width: horizontalScale(360),
    height: verticalScale(66),
    position: 'absolute',
    bottom: verticalScale(100),
    alignSelf:'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0099FF',
    paddingVertical: verticalScale(8),
    borderRadius: radiusScale(16),
  },
  fixedButton: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  getAppointmentText: {
    fontFamily: Fonts.Bold,
    fontSize: fontScale(18),
    color: '#FFFFFF',
  },
});
export default styles;
