import {StyleSheet} from 'react-native';
import {
  verticalScale,
  horizontalScale,
  verticalMarginScale,
  horizontalMarginScale,
  radiusScale,
  fontScale,
} from '../../utils/DimensionConstant';
import {Fonts} from '../../utils/Constants';
const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
  },
  header: {
    height: verticalScale(100),
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    padding: 20,
    paddingBottom: 0,
    // backgroundColor:'red',
    marginVertical: verticalMarginScale(10),
  },
  backIcon: {
    height: verticalScale(40),
    width: horizontalScale(40),
  },
  headerTxt: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(22),
    color: '#FFFFFF',
  },
  docImg: {
    height: verticalScale(400),
  },
  midContainer: {
    width: horizontalScale(400),
    height: verticalScale(250),
    justifyContent: 'space-around',
    // backgroundColor: 'red',
    padding: 10,
    marginVertical: verticalMarginScale(10),
    flexDirection: 'row',
  },
  leftContainer: {
    width: '60%',
    // backgroundColor: 'yellow',
  },
  rightContainer: {
    width: '50%',
    height: '90%',
    // backgroundColor: 'green',
    justifyContent: 'space-between',
    marginVertical: verticalMarginScale(20),
  },
  rating: {
    flexDirection: 'row',
    width: horizontalScale(69),
    height: verticalScale(33),
    backgroundColor: '#3BB2FF',
    borderRadius: radiusScale(28),
    justifyContent: 'space-evenly',
    alignItems: 'center',
    paddingHorizontal: horizontalScale(15),
  },
  ratingIcon: {
    width: horizontalScale(15),
    height: verticalScale(15),
  },
  ratingTxt: {
    color: '#FFFFFF',
    fontFamily: Fonts.Bold,
    fontSize: fontScale(13),
    alignItems: 'center',
  },
  docName: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(48),
    color: '#FFFFFF',
  },
  docSpec: {
    width: horizontalScale(89),
    height: verticalScale(28),
    borderRadius: radiusScale(14),
    backgroundColor: '#39AEFA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  docSpecTxt: {
    fontFamily: Fonts.Medium,
    fontSize: fontScale(14),
    color: '#FFFFFF',
    lineHeight: 16,
  },
  docBg: {
    // width: horizontalScale(430),
    height: verticalScale(276),
    borderRadius: radiusScale(24.66),
    paddingVertical: 30,
    paddingHorizontal: 15,
  },
  subContainer1: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalMarginScale(30),
    width: horizontalScale(360),
  },
  subContainer2: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    height: verticalScale(89),
    borderRadius: radiusScale(20),
    // paddingVertical: 30,
    paddingHorizontal: 20,
    width: horizontalScale(360),
  },
  left: {
    flexDirection: 'row',
    width: horizontalScale(130),
    height: verticalScale(50),
    borderRadius: radiusScale(66),
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    paddingVertical: 8,
    paddingHorizontal: 14,
  },
  feesHead: {
    fontFamily: Fonts.Bold,
    fontSize: fontScale(15),
    color: '#323232',
  },
  feesTxt: {
    fontFamily: Fonts.Bold,
    fontSize: fontScale(26),
    color: '#2BBB4B',
    // backgroundColor: 'yellow',
  },
  right: {
    flexDirection: 'row',
    width: horizontalScale(165),
    height: verticalScale(50),
    alignItems: 'center',
    justifyContent: 'space-between',
    // backgroundColor:'red',
  },
  mode: {
    width: horizontalScale(81),
    height: verticalScale(50),
    borderRadius: radiusScale(50.5),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFFA8',
  },
  modeTxt: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(18),
    color: '#0099FF',
  },
  items: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    // backgroundColor:'red',
    width: horizontalScale(90),
  },
  icons: {
    width: horizontalScale(25.14),
    height: verticalScale(25.14),
  },
  txt: {
    fontFamily: Fonts.Bold,
    fontSize: fontScale(14),
    color: '#0099FF',
  },
  head: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(12),
    color: '#878787',
  },
  Container: {
    marginTop: verticalMarginScale(100),
    // width: horizontalScale(400),
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: radiusScale(40),
    borderTopRightRadius: radiusScale(40),
    paddingHorizontal: horizontalScale(25),
    paddingVertical: verticalScale(20),
  },
  aboutContainer: {
    marginVertical: verticalMarginScale(10),
  },
  aboutHead: {
    fontFamily: Fonts.Bold,
    fontSize: fontScale(18),
    color: '#323232',
    marginBottom: verticalMarginScale(8),
  },
  aboutTxt: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(14),
    color: '#323232',
  },
  viewTxt: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(14),
    color: '#0B57DF',
  },
  locationContainer: {
    height: verticalScale(139),
    // width: horizontalScale(400),
    borderWidth: 1,
    borderRadius: radiusScale(24),
    borderColor: '#F1F1F1',
    paddingVertical: verticalScale(15),
    paddingHorizontal: horizontalScale(15),
    marginVertical: verticalMarginScale(15),
  },
  locationHead: {
    fontFamily: Fonts.Bold,
    fontSize: fontScale(18),
    color: '#323232',
    marginVertical: verticalMarginScale(5),
  },
  addressContainer: {
    flexDirection: 'row',
    marginVertical: verticalMarginScale(5),
  },
  addressIcon: {
    height: verticalScale(24),
    width: horizontalScale(22.06),
    marginRight: horizontalMarginScale(5),
  },
  addressTxt: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(16),
    color: '#323232',
  },
  languageContainer: {
    height: verticalScale(85),
    borderWidth: 1,
    borderRadius: radiusScale(24),
    borderColor: '#F1F1F1',
    paddingHorizontal: horizontalScale(18),
    paddingVertical: verticalScale(16),
    marginBottom: verticalMarginScale(15),
    justifyContent: 'center',
  },
  languageHead: {
    fontFamily: Fonts.Bold,
    fontSize: fontScale(18),
    color: '#323232',
    marginVertical: verticalMarginScale(5),
  },
  languageTxt: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(16),
    color: '#323232',
  },
  r2Container: {
    height: verticalScale(389),
    borderWidth: 1,
    borderRadius: radiusScale(24),
    borderColor: '#F1F1F1',
    paddingHorizontal: horizontalScale(24),
    paddingVertical: verticalScale(24),
  },
  r2Head: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginBottom: verticalMarginScale(20),
    // backgroundColor:'red',
  },
  r2HeadTxt: {
    fontFamily: Fonts.Bold,
    fontSize: fontScale(18),
    color: '#292D32',
  },
  r2HeadBtn: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(14),
    color: '#555B6C',
  },
  line: {
    width: horizontalScale(305),
    borderWidth: radiusScale(0.7),
    borderColor: '#F1F1F1',
    alignItems: 'center',
    // margin:'auto',
  },
  ratingContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: verticalMarginScale(20),
    // backgroundColor:'red',
  },
  leftRating: {
    width: horizontalScale(191),
    height: verticalScale(50),
    // backgroundColor:'green',
  },
  leftTxt: {
    fontFamily: Fonts.Bold,
    fontSize: fontScale(40),
    color: '#292D32',
  },

  rightRating: {
    width: horizontalScale(100),
    height: verticalScale(48),
    // backgroundColor:'red',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  starContainer: {
    flexDirection: 'row',
  },
  star: {
    width: horizontalScale(20),
    height: verticalScale(20),
  },
  rightTxt: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(16),
    color: '#555B6C',
  },
  card: {
    // width: horizontalScale(336),
    height: verticalScale(62),
    marginVertical: verticalMarginScale(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    // backgroundColor:'yellow',
  },
  leftDetails: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rightDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    width: horizontalScale(45),
    height: verticalScale(32),
    // backgroundColor:'red',
    justifyContent: 'space-around',
  },
  profileImg: {
    width: horizontalScale(62),
    height: verticalScale(62),
    borderRadius: radiusScale(50),
    marginRight: horizontalMarginScale(10),
  },
  userName: {
    fontFamily: Fonts.Bold,
    fontSize: fontScale(18),
    color: '#292D32',
  },
  userActive: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(16),
    color: '#555B6C',
  },
  starIcon: {
    width: horizontalScale(20),
    height: verticalScale(20),
  },
  starRating: {
    fontFamily: Fonts.SemiBold,
    fontSize: fontScale(16),
    color: '#FFB063',
  },
  fixedButtonContainer: {
    width: horizontalScale(360),
    height: verticalScale(70),
    position: 'absolute',
    left: 14,
    top: 520,
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#0099FF',
    paddingVertical: verticalScale(8),
    borderRadius: radiusScale(102),
  },
  innerContainer: {
    width: horizontalScale(340),
    height: verticalScale(55),
    paddingVertical: verticalScale(8),
    borderRadius: radiusScale(102),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    // backgroundColor:'red',
    paddingRight: horizontalScale(5),
  },
  rightArrowContainer: {
    width: horizontalScale(52),
    height: verticalScale(52),
    borderRadius: radiusScale(40),
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rightArrow: {
    width: horizontalScale(20),
    height: verticalScale(20),
  },
  bookNowText: {
    fontFamily: Fonts.Bold,
    fontSize: fontScale(16),
    color: '#FFFFFF',
  },
});
export default styles;
